"""Axiom ordered-point evaluator public API."""

from .comparison import compare, compare_runs
from .domain import (
    ORDERED_POINT_DOMAIN_PACK,
    DomainPack,
    MetricDefinition,
    get_domain_pack,
    list_domain_packs,
    register_domain_pack,
)
from .evaluator import evaluate
from .experiment import contour_ab_example, run_experiment
from .models import (
    CaseOutcome,
    Claim,
    ClaimStatus,
    ComparisonOperand,
    ComparisonReport,
    ComparisonSpec,
    CompatibilityIssue,
    CompatibilityReport,
    EvaluationReport,
    EvaluationRequest,
    ExperimentArm,
    ExperimentArmResult,
    ExperimentReport,
    ExperimentSpec,
    ExecutionStatus,
    MetricComparison,
    MetricStatus,
    Observation,
    ParameterSet,
    Run,
    RunBundle,
    RunSpec,
    SubjectDefinition,
)
from .run import evaluate_run
from .subjects import list_subjects, register_subject

__all__ = [
    "Claim",
    "ClaimStatus",
    "CaseOutcome",
    "ComparisonOperand",
    "ComparisonReport",
    "ComparisonSpec",
    "CompatibilityIssue",
    "CompatibilityReport",
    "compare",
    "compare_runs",
    "DomainPack",
    "EvaluationReport",
    "EvaluationRequest",
    "ExperimentArm",
    "ExperimentArmResult",
    "ExperimentReport",
    "ExperimentSpec",
    "ExecutionStatus",
    "evaluate_run",
    "MetricStatus",
    "MetricComparison",
    "MetricDefinition",
    "Observation",
    "ParameterSet",
    "ORDERED_POINT_DOMAIN_PACK",
    "get_domain_pack",
    "list_domain_packs",
    "register_domain_pack",
    "Run",
    "RunBundle",
    "RunSpec",
    "SubjectDefinition",
    "contour_ab_example",
    "evaluate",
    "list_subjects",
    "register_subject",
    "run_experiment",
]
