<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Axiom.OpcUaShadow.Conformance</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Axiom.OpcUaShadow.Adapter/Axiom.OpcUaShadow.Adapter.csproj" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server" />
  </ItemGroup>
</Project>
