<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Axiom.OpcUaShadow.BeckhoffPermissionVerifier</AssemblyName>
    <RootNamespace>Axiom.OpcUaShadow.BeckhoffPermissionVerifier</RootNamespace>
    <Version>0.2.0</Version>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Axiom.OpcUaShadow.Adapter\Axiom.OpcUaShadow.Adapter.csproj" />
  </ItemGroup>
</Project>
